# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4d3584e8e20a70884a0d692cbb57c03dfcefba7ab3106dad67dc03f81eb6ae2dee200fd8648fdc1e196ad3b181c1c01828ffe1db00137542b4ea25e41af3373

test:
  secret_key_base: d6ddcdaad29047f4d778fb336f46aec76f88a329f19319fd9f8cbd964fcf1820d7a3dbc63576f63d208c10d497747c3bc758422448eb4fe88f0e92470fb04846

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
